apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 3  # Adjust the number of replicas as desired

  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
      - name: mongodb
        image: mongo:latest  # MongoDB image from DockerHub
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin  # Replace with your desired MongoDB root username
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password  # Replace with your desired MongoDB root password
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"

      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc  # Replace with the name of your persistent volume claim
